### ISSUE TITLE
Different numbers in the "downloaded files" and "number of downloads" columns after downloading the blog due to the presence of duplicates in the blog

### ISSUE THREAD

**Issue by Taranchuk** [johanneszab/TumblThree#39]
If the blog contains a certain number of duplicates, which the program misses, then the "downloaded files" and "number of downloads" columns display different numbers after downloading. Say, the blog contains 1000 images, 50 of which are duplicates, then the program shows that 950 images have been downloaded and the "number of downloads" column displays a number of 1000 images. Because of this the progress bar becomes incomplete, does not reach a bit until the end, and therefore it seems that the blog has not downloaded completely. It would be convenient if you did so that the number of "number of downloads" would be less by the number of duplicates then it would be clear that the blog was downloaded completely

**Comment by Taranchuk** [comment]
It turned out I at first did not understand the principle of the column "the number of downloads." It shows the total number of posts for all types: texts, images, video, audio and metadata. And I only download images and their metadata. So if the blog contains 1000 images, 100 videos and 1000 metadata images, then the "downloads" column will show the number 2000, and in the "number of downloads" column will show the number 2100, so even after reducing the number of downloads by the number of duplicates, the program will still be show different numbers between these columns. Is it possible to change this, let's say that the program took the number of downloads from the activated download modes, for example if the modes of downloading images and their metadata are selected, then the total number of posts is taken only from them?

**Comment by johanneszab** [comment]
I think I've fixed it in the .27 release.

Thanks again for testing!

**Comment by Taranchuk** [comment]
johanneszab, I downloaded the version 1.0.4.27 three day ago, the program still shows different numbers in the columns due to the presence of duplicates in the blogs.

**Comment by johanneszab** [comment]
Well, people will complain either way. If we subtract the the duplicates, people will come and complain that TumblThree downloads/detects less files than _xxx downloader_.

Honestly, I couldn't care less. For me it's mostly cosmetic. There are more important things to fix.

I've subtracted the duplicates now. I can guarantee you, someone will come and complain.

**Comment by Taranchuk** [comment]
Thank you! Maybe it makes sense to written in a detail view of blogs that out of a total number of posts xxx duplicates were deducted? So that people would understand and they would not complain?

**Comment by CoWinkKeyDinkInc** [comment]
This still seems like a problem in 1.0.8.68
